version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 15001:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin